### ISSUE TITLE
HTTP Error 500

### ISSUE THREAD

**Issue by Cha14ka** [ading2210/vercel-llm-api#4]
Sometimes it does not get a response from the first time. It gives out HTTP Error 500. I have to do while true until it responds

Simple code:
```import vercel_ai
client = vercel_ai.Client()
result = ""
for chunk in client.generate("openai:gpt-3.5-turbo", "Summarize the GNU GPL v3"):
  result += chunk
print(result)
```

Gives this error:

```Traceback (most recent call last):
  File "/home/cha14ka/.local/lib/python3.11/site-packages/vercel_ai.py", line 130, in stream_request
    chunk = chunks_queue.get(block=True, timeout=0.01)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cha14ka/git/gpt4free/kbotgpt.py", line 34, in <module>
    for chunk in client.chat("openai:gpt-3.5-turbo", chat):
  File "/home/cha14ka/.local/lib/python3.11/site-packages/vercel_ai.py", line 133, in stream_request
    raise error
  File "/home/cha14ka/.local/lib/python3.11/site-packages/vercel_ai.py", line 121, in request_thread
    response.raise_for_status()
  File "/home/cha14ka/.local/lib/python3.11/site-packages/curl_cffi/requests/cookies.py", line 51, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 500: 
```

**Comment by Cha14ka** [comment]
Oh, that seems to be a problem on their site.

![image](https://github.com/ading2210/vercel-llm-api/assets/16352397/3e40f20c-418f-431e-a9ac-d4c305a3d381)
