### ISSUE TITLE
Issues while making prompts with Cyrillic characters.

### ISSUE THREAD

**Issue by FanaticExplorer** [ading2210/vercel-llm-api#8]
When I send `openai:gpt-3.5-turbo` a chat request on russian (for example, "_Расскажи больше про себя_"), i get an error:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/curl_cffi/curl.py", line 53, in write_callback
    callback(ffi.buffer(ptr, nmemb)[:])
  File "/home/vercel_ai.py", line 123, in callback
    chunks_queue.put(data.decode())
                     ^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 0: unexpected end of data
```
And when I make a chat on Ukrainian with the same model, it gives only part of the text. For example, "_Розкажи більше про себе_" returned
```
Звісно, я з радістю розповім більше про себе! 

... //answers like usual

Щодо моїх функцій, я можу допомогти вам з по
```
And that's all; it didn't finished his answer.

**Comment by kapitankuba20111** [comment]
In the code, you just replace `data.decode()` at line 123 with `data.decode("latin1")`

**Comment by FanaticExplorer** [comment]
Somehow, while trying to ask on russian, i got whole new error:
```python
Traceback (most recent call last):
  File "/home/vercel_ai.py", line 137, in stream_request
    chunk = chunks_queue.get(block=True, timeout=0.01)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/queue.py", line 179, in get
    raise Empty
_queue.Empty
```

**Comment by FanaticExplorer** [comment]
Any progress?

**Comment by 0x6a69616e** [comment]
We're stuck on an entirely different issue which renders the library unusable 😅

See issue #22
